import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/form.module.css'
import axios from 'axios';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useState } from 'react';


export default function Home() {
  const [name,setName] = useState('');
  const [address,setAddress] = useState('')
  const [password,setPassword] = useState('')
  const [email,setEmail] = useState('')


  const saveNmae = async() =>{
    let res = await axios.post('https://63074e69c0d0f2b8012bf895.mockapi.io/form_data',{
      name: name,
      address:address,
      password: password,
      email: email
    })
    .then(function (response) {
      console.log('stored succesfully');
    })
  }
  // axios.post('https://63074e69c0d0f2b8012bf895.mockapi.io/form_data', {
  //   name: 'Priya keshari',
  //   address: 'varanasi'
  // })
  // .then(function (response) {
  //   console.log(response);
  // })
  // .catch(function (error) {
  //   console.log(error);
  // });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br></br><br></br>
      <div className={styles.form1}>
      <Form>
      <Form.Group className="mb-3" controlId="formBasicName">
        <Form.Label  className={styles.address}>Name :</Form.Label>
        <div className={styles.email}>
        <Form.Control type="Name" placeholder="Enter name" onChange={(e)=>{setName(e.target.value)}}/>
        </div>
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicAddress">
        <Form.Label  className={styles.address}>Address :</Form.Label>
        <div className={styles.email}>
        <Form.Control type="Address" placeholder="Enter address" onChange={(e)=>{setAddress(e.target.value)}}/>
        </div>
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label className={styles.address}>Email :</Form.Label>
        <div className={styles.email}>
        <Form.Control type="email" placeholder="Enter email" onChange={(e)=>{setEmail(e.target.value)}} />
        <div className={styles.address}>
        <Form.Text className="text-muted">
          We'll never share your email with anyone else.
        </Form.Text></div>
        </div>
      </Form.Group>

      <Form.Group className="mb-3" controlId="formBasicPassword">
        <Form.Label  className={styles.address}>Password :</Form.Label>
        <div className={styles.email}>
        <Form.Control type="password" placeholder="Password" onChange={(e)=>{setPassword(e.target.value)}} />
        </div>
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicCheckbox">
        <Form.Check  className={styles.address} type="checkbox" label="Check me out" />
      </Form.Group>
      <Button  className={styles.address} variant="primary" onClick= {saveNmae }>
        Submit
      </Button>
    </Form> 
    </div>

      <main className={styles.main}>
       <h1 className={styles.titles}>
        {/* <h6>Form</h6> */}
       </h1>

        
      </main>

      
    </div>
  )
}
