import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import 'bootstrap/dist/css/bootstrap.min.css';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import Nav from 'react-bootstrap/Nav';
import Form from 'react-bootstrap/Form';
import Tabs from 'react-bootstrap/Tabs';
import Tab from 'react-bootstrap/Tab';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <container>
     <Row>
            <Col md={9} sm={12}>
               <div className={styles.first}>
                <div className={styles.c2}>
                <div className={styles.c1}>
                  <div className={styles.c3}>
                    <p>classic 350 (2012-2022)</p><span>Comfort</span>
                 </div>
                 </div>
                </div>
               <hr></hr>
               <h3 className={styles.h33}>Q. What's the Minimum height of a person required to drive a Classic 350?</h3>
                                        <div className={styles.p}>
                                                      <div className={styles.bar}>             <p > <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
                                  </svg>16.1K Views | </p>
                                                <p>  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
                                        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
                                      </svg> Add Answer</p>
                                      </div>    </div><hr></hr>
                                      <p>31 Answers</p>
                                      <Row>
                     <Col md={1} sm={2} xs={2}>
              <div>
                <h1 className={styles.tit}>P</h1>
              </div>
              </Col>

              <Col md={11} sm={10} xs={10}>
              <div >
               
               <div className={styles.bar}>
                 <p className={styles.bar1} >Jatav </p>
                <p>| 1 Year ago</p>
                </div>
                <div className={styles.triangle}></div>
                <div className={styles.ans}>
                  <div className={styles.ans2}>
                    @ Vasanth | 5.5 inches is perfect minimum height for RE classic 350
                  </div>
                  Are you mad bro if you were riding bullet with 1 or 2 guy...being leg not touches the ground you are gonna suffer too much..If there will be some holes like ding on the road..You are gone...5.8 is enough to handle
                </div>
                
                
              </div>
              
               
               <div className={styles.bar}>
                 <svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
  <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
</svg> 
<p className={styles.img1}>0 </p>
<p className={styles.img2}>|</p>
                <p className={styles.img3}>  Reply</p>
                </div>
                <h5 className={styles.h31}>View 3 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                </Col>
                <Row>
                  <Col md={1} sm={2} xs={2}>
                    <div><h1 className={styles.tit}>P</h1> </div>
                  </Col>
                  <Col md={11} sm={10} xs={10}>
                    <div>
                    <div className={styles.bar}>
                 <p className={styles.bar1} >Abhay </p>
                <p>| 1 Year ago</p>
                </div>
                <p>Am just 5.2 (160cm). Riding classic 350 for two years without any seat adjustment. Havent faced any issues so far.. If you are confident you can tame it easily</p>
                    </div>
                    <div className={styles.bar}>
                 <svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
  <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
</svg> 
<p className={styles.img1}>0</p>
<p className={styles.img2}>|</p>
                <p className={styles.img3}>  Reply</p>
                </div>
                <h5 className={styles.h31}>View 3 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                  </Col>
                </Row>
                <Row>
                  <Col md={1} sm={2} xs={2}>
                    <div><h1 className={styles.tit}>P</h1></div>
                  </Col>
                  <Col md={11} sm={10} xs={10}>
                     <div className={styles.bar}>
                 <p className={styles.bar1} >Vasanth </p>
                <p>| 1 Year ago</p>
                </div>
                <div className={styles.triangle}></div>
                <div className={styles.ans}>
                  <div className={styles.ans1}>
                    @ jatan | Are you mad bro if you were riding bullet with 1 or 2 guy...being leg not touches the ground you are gonna suffer too much..If there will be some holes like ding on the road..You are gone...5.8 is enough to handle
                  </div>
                  Hi
                </div>
                <div className={styles.bar}>
                 <svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
  <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
</svg> 
<p className={styles.img1}>0</p>
<p className={styles.img2}>|</p>
                <p className={styles.img3}>  Reply</p>
                </div>
                
                <h5 className={styles.h31}>View 3 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
              
                
                  </Col>
                </Row>
                </Row>                   
               </div>
               </Col>
               
            <Col md={3} sm={3} xs={3}>
              <div className={styles.first}>
               <div className={styles.flex}>
               <p className={styles.hr}>Trending Royal Enfield Bikes</p>
               <p className={styles.hr1}>View All</p>
               
               </div>
               <div className={styles.bar2}>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                    <img src="p1.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Bullet 350</p>
                    <p className={styles.hr2}>Rs.1.47 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Interceptor</p>
                    <p className={styles.hr2}>Rs.2.88 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p5.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Continental GT 650</p>
                    <p className={styles.hr2}>Rs.3.05 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p6.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Classic 350</p>
                    <p className={styles.hr2}>Rs.1.90 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Meteor 350</p>
                    <p className={styles.hr2}>Rs.3.01 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Meteor 350</p>
                    <p className={styles.hr2}>Rs.3.01 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Meteor 350</p>
                    <p className={styles.hr2}>Rs.3.01 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Meteor 350</p>
                    <p className={styles.hr2}>Rs.3.01 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="p4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Meteor 350</p>
                    <p className={styles.hr2}>Rs.3.01 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               </div>
               </div>
            </Col>
            
     </Row>
     
     </container>
     
     
      
        

      
      <main className={styles.main}>
          
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
