import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/garage.module.css'
import container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import 'bootstrap/dist/css/bootstrap.min.css';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import Form from 'react-bootstrap/Form';
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import Accordion from 'react-bootstrap/Accordion';
import axios from 'axios';
import { useState } from 'react';


const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 3000 },
    items: 5
  },
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 3
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 2
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1
  }
};
export default function Home() {
  const [reply,setReply] = useState('');


  const saveReply = async() =>{
    let res = await axios.post('https://63074e69c0d0f2b8012bf895.mockapi.io/form_data',{
      reply: reply,
    })
    .then(function (response) {
      console.log('stored succesfully');
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <container>
        <Row>
          <div className={styles.car}>
          <img src="/logo.webp"></img>
          
          </div><hr></hr>
          <Col md={1} sm={12}>
            <div className={styles.fc}>
              <img src="/b1.jpg" width="50px" height="50px"></img>
              </div>
          </Col>
          <Col md={8} sm={12}>
            <div className={styles.box2}>
                   <div className={styles.box1}>
                     <div className={styles.box}>
                        <p>Baleno 2015-2022</p><span>Safety</span>
                      </div>
                     </div>
                   </div><hr></hr>
             <h1 className={styles.h1}>Q. How safe is Baleno Zeta on highways?</h1> 
              <div className={styles.p}>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                   <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                      <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                    </svg>2.1k Views |</p>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
                      </svg>Add Answer</p>
              </div>  <hr></hr> 
            <Row>
               <p className={styles.h2}>7 Answers</p> 
                   <Col md={1} sm={12}>
                     <div>
                         <h2 className={styles.tit}>P</h2>
                     </div>
                   </Col>
                  <Col md={10} sm={12}>
                    <div className={styles.head}>
                      <p className={styles.head1}>Rohith </p>
                       <p> | 3 years ago</p>
                    </div>
                      <div  className={styles.ti1}>
                           <p className={styles.ti}>All varients of baleno comes with standard safety equipment like front dual airbags ebd abs etc..., if you search on internet there are some videos showing alott off damage on baleno in minor accident, this is because every manufacturer have different
                           approch to provide safety, in maruti case they gave alot of crumple Zone to absorb any hits. If you open hood and see engine bay there is alot of space between radiator and enginr, in petrol its huge. This crumple Zone gets damaged in small accidents also but cost of repair is not high. My bumper got hit once(preety bad).Cost to replace it is 8k for entire piece. Compara...<span>Read More</span></p>
                       </div>
                       <div className={styles.bar}>
                        <p><svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                           <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                             </svg></p>
                             <p className={styles.img1}> 5 </p>
                               <p className={styles.img2}>|</p>
                                      </div>


                            <div className={styles.repl1}>
                               <Accordion className={styles.reply5}>
                                    <Accordion.Item eventKey="0">
                                      <Accordion.Header className={styles.repl2}><p>Reply</p></Accordion.Header>
                                        <Accordion.Body className={styles.repl3}>
                                        <Form>
                       <Form.Group className="mb-3" controlId="example Form.ControlTextarea1">
                       <Form.Control as="textarea"  onChange={(e)=>{setReply(e.target.value)}} rows={5} placeholder="Add your Reply"/>
                       </Form.Group>
                       <div className={styles.btn2}>
                        <Button className={styles.btn1}>Cancle</Button>
                        <Button className={styles.btn3} onClick= {saveReply}>Submit</Button>
                        </div>
                       </Form>
                                        </Accordion.Body>
                                    </Accordion.Item>
                                 </Accordion>
                               </div>           
                  </Col>
            </Row>
            <Row>
              <Col md={1} sm={12}>
                 <div>
                 <h2 className={styles.tit}>P</h2>
                 </div>
              </Col>
              <Col md={10} sm={12}>
                 
                 <div className={styles.head}>
                      <p className={styles.head1}>Abhash</p>
                       <p> | 3 years ago</p>
                    </div>
                    <div>
                        <p className={styles.ti}>Its preety safe.. 2 air bags are not enough though! But ABS is intuitive and driving dynamics (ride and handling) are very stable.triple digit speed is a breeze affair! But still drive slow and safely!</p>
                    </div>
                    <div className={styles.bar}>
                        <p><svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                           <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                             </svg></p>
                             <p className={styles.img1}> 4 </p>
                               <p className={styles.img2}>|</p>
                                 <p className={styles.img3}>  Reply</p>
                                 <p><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16"><path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/></svg></p>
                </div>
              </Col>
            </Row>
            <Row>
              <Col md={1} sm={12}>
                <div>
                   <h2 className={styles.tit}>P</h2>
                </div>
              </Col>
              <Col md={10} sm={12}>
              <div className={styles.head}>
                      <p className={styles.head1}>Jashan</p>
                       <p> | 3 years ago</p>
               </div>
               <div>
                        <p className={styles.ti}>Very safe, even at highspeed car maintain its stability. ABS works well </p>
                </div>
                <div className={styles.bar}>
                        <p><svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                           <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                             </svg></p>
                               <p className={styles.img1}> 3 </p>
                                 <p className={styles.img2}>|</p>
                             <p className={styles.img3}>  Reply</p>
                             <p><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16"><path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/></svg></p>
                           </div>
                           
                           
                         </Col>
                       </Row>
                       <Row>
              <Col md={1} sm={12}>
                 <div>
                 <h2 className={styles.tit}>P</h2>
                 </div>
              </Col>
              <Col md={10} sm={12}>
                 
                 <div className={styles.head}>
                      <p className={styles.head1}>Bhoop</p>
                       <p> | 3 years ago</p>
                    </div>
                    <div>
                        <p className={styles.ti}>Safe and secure car because the abs works perfectly https://www.Zigwheels.com/newcars/Maruti-Suzuki/Baleno/specifications</p>
                    </div>
                    
                    <div className={styles.bar}>
                        <p><svg className={styles.img} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                           <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                             </svg></p>
                             <p className={styles.img1}> 2 </p>
                               <p className={styles.img2}>|</p>
                                 <p className={styles.img3}>  Reply</p>
                                 
                                 <p className={styles.display}><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16"><path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/></svg></p>
                </div>
                <h5 className={styles.h31}>View More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
              </Col>
            </Row>
                         
                     <Row className={styles.bg}>
                     <div className={styles.ans2}>
                         <div className={styles.chat}>
                          <img src="/b.jpg" height="40px" width="40px"></img>
                          </div>
                          <p className={styles.bold}>Add your Answer</p></div>
                          <div className={styles.ans1}>
                          
                       </div> 
                       <Form>
                       <Form.Group className="mb-3" controlId="example Form.ControlTextarea1">
                       <Form.Control as="textarea" rows={5} placeholder="Have something to say..." />
                       </Form.Group>
                        <Button className={styles.btn}>Submit Answer</Button>
                       </Form>
                    </Row> 
                           <div className={styles.bg1}>
                           <div className={styles.from}> From The Community</div>
                        <Carousel responsive={responsive}>
                          
                          <div className={styles.back}>
                            <div className={styles.bold2}>Q. What is the difference between 2018 petrol Baleno...</div>
                            <div className={styles.flex1}>
                            <div>  <h2 className={styles.t1}>P</h2></div>
                            <div className={styles.askby}>Asked by Hanumantappa Budihal 4 Answers</div>
                            </div>
                          </div>
                          <div className={styles.back}>
                            <div className={styles.bold2}>Q. Is there any change in Maruti Baleno 2019 in inter...</div>
                            <div className={styles.flex1}>
                            <div>  <h2 className={styles.t1}>P</h2></div>
                            <div className={styles.askby}>Asked by Radhrshyam Modi</div>
                            </div>
                          </div>
                          <div className={styles.back}>
                            <div className={styles.bold2}>Q. Are there going to be any changes to the steering...</div>
                            <div className={styles.flex1}>
                            <div>  <h2 className={styles.t1}>P</h2></div>
                            <div className={styles.askby}>Asked by Mike scott 2 Answers</div>
                            </div>
                          </div>
                          <div className={styles.back}>
                            <div className={styles.bold2}>Q. What is the difference between 2018 petrol Baleno...</div>
                            <div className={styles.flex1}>
                            <div>  <h2 className={styles.t1}>P</h2></div>
                            <div className={styles.askby}>Asked by Hanumantappa Budihal 4 Answers</div>
                            </div>
                          </div>
                          <div className={styles.back}>
                            <div className={styles.bold2}>Q. Is there any change in Maruti Baleno 2019 in inter...</div>
                            <div className={styles.flex1}>
                            <div>  <h2 className={styles.t1}>P</h2></div>
                            <div className={styles.askby}>Asked by Radhrshyam Modi</div>
                            </div>
                          </div>
                          <div className={styles.back}>
                            <div className={styles.bold2}>Q. Are there going to be any changes to the steering...</div>
                            <div className={styles.flex1}>
                            <div>  <h2 className={styles.t1}>P</h2></div>
                            <div className={styles.askby}>Asked by Mike scott 2 Answers</div>
                            </div>
                          </div>
                          
                        </Carousel>;<hr></hr>
                        <div className={styles.com}>Community Discussions</div></div>
                        <div className={styles.border}>
                            <div className={styles.com1}>Related Questions</div>  
                            </div>                
                     </Col> 
                      
                        
                      
                      
                        
                        
                        
                      
                     
                     
           
           
           <Col md={3} sm={12}>
           <div className={styles.first}>
               <div className={styles.flex}>
               <p className={styles.hr}>Trending Royal Enfield Bikes</p>
               <p className={styles.hr1}>View All</p>
               
               </div>
               <div className={styles.bar2}>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                    <img src="a8.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Brezza</p>
                    <p className={styles.hr2}>Rs. 7.99 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a2.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Swift</p>
                    <p className={styles.hr2}>Rs. 5.91 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a3.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Alto k10</p>
                    <p className={styles.hr2}>Rs. 3.99 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Baleno</p>
                    <p className={styles.hr2}>Rs. 6.49 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a5.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>ertiga</p>
                    <p className={styles.hr2}>Rs. 8.35 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a6.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Brezza</p>
                    <p className={styles.hr2}>Rs. 7.99 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a8.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Swift</p>
                    <p className={styles.hr2}>Rs. 5.91 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a2.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Alto k10</p>
                    <p className={styles.hr2}>Rs. 3.99 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="a4.jpg"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Baleno</p>
                    <p className={styles.hr2}>Rs. 6.49 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               </div>
               </div>
           </Col>
          </Row>

        </container>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
